name: "Update supported locales"

on:
  push:
    branches: [main]

jobs:
  updateSupportedLocales:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Update supported locales file
        run: npm run update-locales

      - name: Create Pull Request if 'src/assets/supported_locales.json' file was changed
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update supported Locales"
          branch: "update_locals/patch"
          delete-branch: true
          title: Update supported locals
          body: "The [update_supported_locales](https://github.com/rickstaa/github-emoji-picker/actions/workflows/update_supported_locales.yml) action found new locales."
          labels: "ci, locales"
